# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64" #Ubuntu 18.04
   config.vm.hostname = "fabric"
   config.vm.network "public_network"
   config.vm.base_address = "192.168.178.201"
   config.vm.base_mac = "0800278A8081"
   config.vm.synced_folder ".", "/vagrant"
      
   #config.disksize.size = '50GB'         
# --------------------------------------------------------------------
   config.vm.provider "virtualbox" do |vb|
      vb.gui = false
	  vb.name = "Fabric"
	  vb.cpus = 2
	  vb.memory = 4096	  	                  
   end
# --------------------------------------------------------------------
end

