---
################################################################################
#   SECTION: Organizations
################################################################################
Organizations:
    - &OrdererOrg        
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: configcr/ordererOrganizations/example.com/msp

    - &Org1        
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: configcr/peerOrganizations/org1.example.com/msp
        AnchorPeers:           
            - Host: peer0.org1.example.com
              Port: 7051

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults    
    Organizations:

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    # Available types are "solo" and "kafka"
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:        
        Brokers:
            - 127.0.0.1:9092    
    Organizations:

################################################################################
#   SECTION: Profile
################################################################################
Profiles:
    OneOrgGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
    OneOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1

