apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-basic
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:     
      app: pod-volume      
  template:
    metadata:
      labels:
        app: pod-volume
    spec:
      containers:
      - name: shell
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
        volumeMounts:
        - name: myvolume
          mountPath: "/tmp/persistent"
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: pvc-basic