apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-full
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:     
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: mypv
    spec:
      containers:
      - name: shell
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
        volumeMounts:
        - name: mypd
          mountPath: "/tmp/persistent"
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim