apiVersion: v1
kind: Pod
metadata:
  name: pod-volume  
  labels: 
    app: sise
spec:
  containers:
  - name: pod-basic
    image: nginx
    volumeMounts:
    - name: vol-secret
      mountPath: /tmp/secret
  volumes:
  - name: vol-secret
    secret:
      secretName: secret-basic
