apiVersion: v1
kind: Pod
metadata:
  name: pod-full
  namespace: samer
spec:
  containers:
  - name: pod-full
    image: quay.io/openshiftlabs/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    env:
    - name: SIMPLE_SERVICE_VERSION
      value: "1.0"
    volumeMounts:
      - name: apikeyvol
        mountPath: "tmp/apikey"
        readOnly: true
  nodeSelector:
    shouldrun: here
  volumes:
  - name: apikeyvol
    secret:
      secretName: apikey
