apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-basic
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: pvc-basic
  hostPath:
    path: "/tmp/data"

