apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-full
  labels:
    type: local  
spec:
  storageClassName: manual                  # Values: Non, manual
  volumeMode: Filesystem                    # Values: Filesystem, Block  
  persistentVolumeReclaimPolicy: Retain     # Values: Retain, Recycle, Delete
  accessModes:
  - ReadWriteMany                           # Values: ReadWriteOnce, ReadWriteMany, ReadOnlyMany
  capacity:
    storage: 200Mi  
  claimRef:
    name: pvc-full
  hostPath:
    path: "/tmp/data"
  # nfs:
  #   server: 172.17.0.2
  #   path: /tmp    
  #   readOnly: false