apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local  
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi  
  hostPath:
    path: /tmp/data  
  # nfs:
  #  server: 172.17.0.2
  #  path: /tmp    
  #  readOnly: false